modLoader = "javafml"
loaderVersion = "[43,)"
license = 'CC0-1.0'

[[mods]]
modId = "sliceanddice"
version = "${file.jarVersion}"
displayName = "Create Slice & Dice"
authors = "possible_triangle"
description = '''Making automation for Farmers Delight more sensible'''

[[dependencies.sliceanddice]]
modId = "forge"
mandatory = true
versionRange = "[43.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sliceanddice]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sliceanddice]]
modId = "create"
mandatory = true
versionRange = "[0.5.0i,)"
ordering = "NONE"
side = "BOTH"