modLoader = "javafml"
loaderVersion = "[40,)"
license = "https://github.com/${repository}/blob/1.18.x/LICENSE.txt"
issueTrackerURL = "https://github.com/${repository}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''Making automation for Farmers Delight more sensible'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[40.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
mandatory = true
versionRange = "[0.5.1.a,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "BOTH"